# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
  storages:
    books.images.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/public%app.path.book_thumbnails%'
        permissions:
          file:
            public: 0755
            private: 0755
          dir:
            public: 0755
            private: 0755
