vich_uploader:
    db_driver: orm

    mappings:
        book_thumbnails:
            uri_prefix: '%app.path.book_thumbnails%'
            upload_destination: books.images.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
