version: '3'

services:
  #  php:
  #    build:
  #      context: ./
  #      dockerfile: ./docker-compose/php/Dockerfile
  #    volumes:
  #      - ./:/var/www/positron:rw
  #    depends_on:
  #      - database
  #    user: www-data
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-positron}
      MYSQL_USER: ${MYSQL_USER:-positron}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: "root_pwd"
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
#  queue:
#    image: redis:7.0-alpine3.16
#    ports:
#      - "6379:6379"
#  nginx:
#    image: nginx:1.8.1-alpine
#    ports:
#      - '80:80'
#    volumes:
#      - ./docker-compose/nginx:/etc/nginx/conf.d:ro
#      - ./var/log/nginx:/var/log/nginx:rw
#      - ./:/var/www/positron:ro
#    depends_on:
#      - php
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
