version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-positron}
      MYSQL_USER: ${MYSQL_USER:-positron}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: "root_pwd"
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
