version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database_test:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: test_positron_test
      MYSQL_USER: positron_test
      MYSQL_PASSWORD: password_test
      MYSQL_ROOT_PASSWORD: root_pwd_test
    volumes:
      - db-data-test:/var/lib/mysql:rw
    ports:
      - "23306:3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
  ###< symfony/mailer ###

volumes:
  db-data-test:
