version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/positron:rw
    ports:
      - "9000"
    depends_on:
      - database
    user: www-data
    working_dir: /var/www/positron
  nginx:
    image: nginx:1.17.9-alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/positron:ro
      - ./var/log/nginx:/var/log/nginx:rw
    ports:
      - '8080:80'
    depends_on:
      - php
  composer:
    image: composer:2.1.6  # PHP ~8.0.0
    working_dir: /var/www/positron
    volumes:
      - ./:/var/www/positron:rw
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-positron}
      MYSQL_USER: ${MYSQL_USER:-positron}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: "root_pwd"
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
#  queue:
#    image: redis:7.0-alpine3.16
#    ports:
#      - "6379:6379"
###< doctrine/doctrine-bundle ###
  node:
    build:
      context: ./docker/node
      dockerfile: ./Dockerfile
    working_dir: /var/www/positron
    volumes:
      - ./:/var/www/positron:rw
    environment:
      - NODE_OPTIONS='--openssl-legacy-provider'

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
