version: '3'

services:
#  php:
#    build:
#      context: ./
#      dockerfile: ./docker-compose/php/Dockerfile
#    volumes:
#      - ./:/var/www/positron:rw
#    depends_on:
#      - database
#    user: www-data
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-positron}
      MYSQL_USER: ${MYSQL_USER:-positron}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: "root_pwd"
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
  database_test:
    image: mysql:${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: test_positron_test
      MYSQL_USER: positron_test
      MYSQL_PASSWORD: password_test
      MYSQL_ROOT_PASSWORD: root_pwd_test
    volumes:
      - db-data-test:/var/lib/mysql:rw
    ports:
      - "23306:3306"
#  nginx:
#    image: nginx:1.8.1-alpine
#    ports:
#      - '80:80'
#    volumes:
#      - ./docker-compose/nginx:/etc/nginx/conf.d:ro
#      - ./var/log/nginx:/var/log/nginx:rw
#      - ./:/var/www/positron:ro
#    depends_on:
#      - php
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
  db-data-test:
###< doctrine/doctrine-bundle ###
